### ISSUE TITLE
Unable to run DPA kernels from the host (non-BF Arm cores)

### ISSUE THREAD

**Issue by max-Hawkins** [RC4ML/BenchBF3#1]
Were you all able to trigger DPA kernels from the 'traditional' (non-BF cores)? I'm able to invoke DPA kernels from the BlueField ARM cores, but not from the x86 host. I see errors similar to those reported on the NVIDIA documentation [here](https://forums.developer.nvidia.com/t/failed-to-run-doca-l2-reflector-on-the-host-side/263717). Considering you heavily benchmarked the DPA, do you have any thoughts on this?

**Comment by cxz66666** [comment]
As far as we know, DOCA 2.7.0(also in latest 2.8.0) only supports programming DPA with Flexio on HOST under NIC MODE, you can convert to NIC MODE and try again!


Here is a simple command for convert DPU MODE to NIC MODE
~~~
sudo mlxconfig -d /dev/mst/mt41692_pciconf0 s INTERNAL_CPU_OFFLOAD_ENGINE=1 

sudo mlxconfig -d /dev/mst/mt41692_pciconf0.1 s INTERNAL_CPU_OFFLOAD_ENGINE=1
~~~

Then power cycle your machine



convet NIC MODE to DPU MODE 
~~~
sudo mlxconfig -d /dev/mst/mt41692_pciconf0 s INTERNAL_CPU_OFFLOAD_ENGINE=0 

sudo mlxconfig -d /dev/mst/mt41692_pciconf0.1 s INTERNAL_CPU_OFFLOAD_ENGINE=0
~~~
Also need power cycle!

**Comment by max-Hawkins** [comment]
Thanks for that! That helps clear things up. 

I appreciate bolding the content "Due to DOCA driver limitation, DPA can only access Arm memory under DPU mode, and access host memory under NIC mode. So please change to correct mode before benchmark.", but I feel that it doesn't make it immediately obvious that it also effects any DPA kernel invocation. I feel like adding something like you said in the previous message would be helpful.

**Comment by cxz66666** [comment]
Thank you so much for the heads up. I will update Readme for that.
